### ISSUE TITLE
CLI support 

### ISSUE THREAD

**Issue by BelkacemYerfa** [BelkacemYerfa/shadcn-extension#25]
This is the issue will track the CLI progress that is intended to be built , to make the setup easier.

CLI will support : 

- [ ] Single component installation
- [ ] All registry installation 
- [ ] Update single component
- [ ] Update all component
- [ ] Get available update for components

How CLI will work :

- Uses the shadcn ui default configuration for the project
- Trigger the shadcn component folder, then add the component in the same folder
